### ISSUE TITLE
Include Metro Vancouver into Vancouver map

### ISSUE THREAD

**Issue by SievaFliesAlone** [KenEucker/biketag-vue#126]
Biketag in Vancouver is played not only within the city boundaries but in the neighbouring municipalities as well (Burnaby, North Vancouver, West Vancouver, Richmond, UBC). Currently there are no technical restrictions and people mostly follow common sense when choosing new mystery locations. As I understand, biketag lications will be displayed on the map at some point, which could lead to people being unable to play in the areas above. Limiting biketag locations to the city of Vancouver only could harm the game.

I suggest including Greater Vancouver, or at least named municipalities, to the Vancouver map.

**Comment by KenEucker** [comment]
At the moment, we don't offer the ability to configure the map boundary that is displayed. This is a feature that would need to be invested in, and would find itself on a roadmap closer to next year if/when that materializes. We are simply using the easiest strategy for displaying a map at the moment. 

As always, the rules and boundaries and everything in between is an active conversation between the community and the BikeTag Ambassadors who volunteer their time to the specific games. In Vancouver, we have Tyrone Siglos as a BikeTag Ambassador and he does an amazing job of working with the community on these issues.

If a tag needs to be removed because it doesn't match the community's expectations of boundary, then the BikeTag Ambassador will handle that. This case-by-case approach focuses less on strictness and more on allowing people to play the game unencumbered.
