### ISSUE TITLE
[BUG] coordinates error in the console blocking uploads

### ISSUE THREAD

**Issue by KenEucker** [KenEucker/biketag-vue#209]
**Describe the bug**
Players are reporting issues with getting uploads to work. One Player was able to provide a screenshot of the error in the console. This appears to do with the retrieval of GPS coordinates from the selected image.

**Expected behavior**
The upload should succeed no matter what, even if the GPS retrieval fails.

**Screenshots**
![Screenshot_from_2024-01-01_23-51-17](https://github.com/KenEucker/biketag-vue/assets/1720267/7be25f1b-c8bf-456e-a22a-763cceaa5f29)

**Additional context**
Additionally, Players are reporting that they no longer see the map popup for choosing the pin of the found location.

**Comment by cookieguru** [comment]
Hopefully #210 fixes this.  The underlying issue may be that the browser is stripping metadata (for privacy): https://github.com/josephfrazier/reported-web/pull/360

**Comment by cookieguru** [comment]
Can confirm that removing [the `accept` attribute](https://github.com/KenEucker/biketag-vue/blob/785f8e911714ce8d5e0f0a53293f9104b9728a45/src/components/QueueFound.vue#L58) will allow exifr to properly read the metadata.  i.e. latitude and longitude are `NaN` when the attribute is present, and they are numbers when the attribute is absent.
Which is pretty annoying, since that attribute hints to the browser which kinds of files are allowed and what kind of file picker to show.

**Comment by KenEucker** [comment]
Hmmm. That's unfortunate. I wonder why it happens _sometimes_.

**Comment by KenEucker** [comment]
This has been resolved.
