### ISSUE TITLE
Style the venomgram starter with the new App Brand

### ISSUE THREAD

**Issue by KenEucker** [KenEucker/biketag-vue#8]
@ItsOkayItsOfficial here's an issue for the work we just discussed that keeps in mind the wireframes and discussion in #1 as well as the assets and screenshots provided in #7. 

This issue can be placed on the Kanban board found in the project: https://github.com/KenEucker/biketag-vue/projects/1

**Comment by ItsOkayItsOfficial** [comment]
Creating branch `scaffold-0.9` to facilitate

**Comment by ItsOkayItsOfficial** [comment]
Social auth to `Google`, `GitHub`, and `Imgur` implemented. Because the Venomgram app UI relied heavily on interpreting user context returned from a custom Venomgram server and Cloudinary to fetch content on the users behalf I'm going to have to clean out that logic and mock returns so that we can see the full UI.

**Comment by KenEucker** [comment]
@ItsOkayItsOfficial 

See #14 for a sample set of JSON for the data that you would get back from sanity.io. The new BikeTag API will wrap the sanity client so we can use that as a drop-in until the BikeTag API is finished, but the sample in that ticket should help you mold your mocked server responses to what we have instead of whatever venomgram's model is.
